<?php

namespace Doctordogg\HelloWorldVMMV\Block;

use Magento\Framework\View\Element\Template;

class Main extends Template {

    /**
     * light status
     *
     * @var string
     */
    protected static $light = 'off';

    protected function _prepareLayout()
    {
        $this->setMessage('Hello Again World!');
        $this->setName($this->getRequest()->getParam('name'));
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    /**
     * Let's try to fire light with usage of <action> tag in layout handle
     *
     */
    public static function lightOn()
    {
        self::$light = 'on';
    }

    /**
     * Let's try to snuff out fire light with usage of <action> tag in layout handle
     *
     */
    public static function lightOff()
    {
        self::$light = 'off';
    }

    /**
     * Let's try to change fire light with usage of <action> tag in layout handle
     *
     * @param string $status
     */
    public static function light(string $status) :void
    {
        self::$light = $status;
    }

    /**
     * Get good bye message
     *
     * @return string
     */
    public function getGoodByeMessage():string
    {
        return 'GoodBye World!';
    }

    /**
     * Get light status
     *
     * @return string
     */
    public function getLightStatus():string
    {
        return self::$light;
    }
}
