<?php

namespace Doctordogg\HelloWorldVMMV\Block;

use Magento\Framework\View\Element\Template;

class Main extends Template {

    protected function _prepareLayout()
    {
        $this->setMessage('Hello Again World!');
        $this->setName($this->getRequest()->getParam('name'));
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getGoodByeMessage()
    {
        return 'GoodBye World!';
    }
}
